// Generated by Wrangler by running `wrangler types`

interface Env {
	QUIZ_RESULTS: KVNamespace;
	CHAT_SESSION: DurableObjectNamespace<import("./src/index").ChatSessionDO>;
	AI: Ai;
	QUIZ_WORKFLOW: Workflow;
}
